# Generated by Django 4.2.9 on 2024-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('webhook_url', models.CharField(max_length=255)),
            ],
        ),
    ]
